// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "gmeet",
    "name": "Google Meet Plugin",
    "description": "Start Google Meeting",
    "homepage_url": "https://github.com/adfinis-forks/mattermost-google-meet-plugin",
    "support_url": "https://github.com/adfinis-forks/mattermost-google-meet-plugins",
    "release_notes_url": "https://github.com/adfinis-forks/mattermost-google-meet-pluginreleases/tag/v0.2.0",
    "icon_path": "assets/starter-template-icon.svg",
    "version": "0.3.0",
    "min_server_version": "6.2.1",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "Google Meet Plugin configurations",
        "footer": "",
        "settings": [
            {
                "key": "GmeetNamingScheme",
                "display_name": "Google Meeting Names:",
                "type": "radio",
                "help_text": "Select how meeting names are generated by default. Users can override this setting with '/gmeet settings'.",
                "placeholder": "",
                "default": "words",
                "options": [
                    {
                        "display_name": "Random English words in title case",
                        "value": "words"
                    },
                    {
                        "display_name": "UUID (universally unique identifier)",
                        "value": "uuid"
                    },
                    {
                        "display_name": "Mattermost context specific names. Combination of team name, channel name, and random text in Public and Private channels; personal meeting name in Direct and Group Message channels.",
                        "value": "mattermost"
                    },
                    {
                        "display_name": "Allow user to select meeting name",
                        "value": "ask"
                    }
                ],
                "hosting": "",
                "secret": false
            }
        ],
        "sections": null
    }
}
`);

export default manifest;
