// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "mattermost-google-meet-plugin",
    "name": "Google Meet Plugin",
    "description": "Start Google Meet calls",
    "homepage_url": "https://github.com/adfinis-forks/mattermost-google-meet-plugin",
    "support_url": "https://github.com/adfinis-forks/mattermost-google-meet-plugins",
    "release_notes_url": "https://github.com/adfinis-forks/mattermost-google-meet-pluginreleases/tag/v0.2.0",
    "icon_path": "assets/starter-template-icon.svg",
    "version": "0.3.0",
    "min_server_version": "6.2.1",
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "Google Meet Plugin configurations",
        "footer": "",
        "settings": [],
        "sections": null
    }
}
`);

export default manifest;
